### PR TITLE
Add simple additive synthesis to sonify scores and performances

### PR DESCRIPTION
**Pull request by neosatrapahereje**
Very simple utility to synthesize `Part`s, `PerformedPart`s and note arrays using additive synthesis

### CODE REVIEW

**Comment by sildater** [comment]
Hey! Very nice and useful. Maybe there should be a usage example in the documentation?

**Review by manoskary — APPROVED** [review]
This PR addresses sonification of score and performance with additive synthesis, and shepart tones. It addas also tests and save wav file using scipy.

**Comment by manoskary** [comment]
- Do we add an example on the documentation???
- Do we merge for version 1.1.0??

**Comment by neosatrapahereje** [comment]
This branch should be merged after merging `unify_score_saving

**Pull request merged**
