### PR TITLE
Voice parsing fix for bug #267

### PR DESCRIPTION
**Pull request by huispaty**
Fixes bug #267 for voice parsing from match files

### CODE REVIEW

**Comment by sildater** [comment]
Thanks for looking into this!

this PR has several problems:
- the implementation of voice parsing were voices are encoded as score attributes "vXYZ" is not working. Currently all match files of the newest version get all voice attributes set to 1 (the reason it's not `none` is the code in lines 747-750 in `importmatch.py`). Please check what strings the number_pattern regex is matching. If the logic is not clear, just ask. 
- it removes prior check for numbers (strings that only contain integers) in the scoreAttributeList. Are you sure this never happens in any match file? Unless you know for certain that the current implementation is unused or your replacement refactors the use case, please **do not remove or change used code and cases** from the library!  
- minor point but it'd still be nice: some unittest for different versions of match files would be great.

**Review by sildater — CHANGES_REQUESTED** [review]
doesn't work yet. not automatically tested. removes potentially used functionality.

**Comment by manoskary** [comment]
> doesn't work yet. not automatically tested. removes potentially used functionality.

The tests were not launched because the initial push was made for the main branch and then changed, an additional commit even an empty one, has to be made to launch the tests. I will do that.

**Comment by sildater** [comment]
> > doesn't work yet. not automatically tested. removes potentially used functionality.
> 
> The tests were not launched 

Thanks! What I meant is the functionality in the PR is not addressed in a unittest.

**Pull request closed without merging**
